{% set name = "pynessie" %}
{% set version = "0.60.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynessie-{{ version }}.tar.gz
  sha256: 7dd9995d7e4be224afe924a0ef23b03cfa80c2bce1c02582e03abd73cd3750e0

build:
  entry_points:
    - nessie=pynessie.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - attrs
    - botocore
    - click <9.0.0,>6.0.0
    - confuse ==2.0.1
    - desert
    - marshmallow
    - marshmallow-oneofschema
    - python-dateutil
    - pyyaml
    - requests
    - requests-aws4auth
    - simplejson

test:
  imports:
    - pynessie
  commands:
    - pip check
    - nessie --help
  requires:
    - pip

about:
  home: https://github.com/projectnessie/nessie
  summary: 'Project Nessie: Transactional Catalog for Data Lakes with Git-like semantics'
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - rxm7706
